from setuptools import setup, find_packages

setup(
    name="khao2",
    version="1.0.0",
    description="Forensics stegananalysis platform - Every single bit.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Odin Glynn-Martin",
    author_email="odin@odinglynn.com",
    maintainer="Odin Glynn-Martin",
    maintainer_email="odin@odinglynn.com",
    url="https://khao2.com",
    project_urls={
        "Homepage": "https://www.khao2.com",
        "Source": "https://github.com/odinglyn0/k2-cli/",
        "Bug Tracker": "https://github.com/odinglyn0/k2-cli/issues",
    },
    packages=find_packages(),
    install_requires=[
        "click>=8.0.0",
        "requests>=2.28.0",
        "pathlib>=1.0.1",
        "typing-extensions>=4.0.0,<4.8.0",
    ],
    entry_points={
        "console_scripts": [
            "k2=khao2.presentation.cli:cli",
        ],
    },
    python_requires=">=3.7",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Security",
        "Topic :: Scientific/Engineering :: Image Processing",
    ],
    keywords="steganography, steganalysis, forensics, image analysis, security",
)
